### ISSUE TITLE
Way to Feed Env File

### ISSUE THREAD

**Issue by PratikThorve** [criteo/newman-server#15]
This is not a issue.
I checked the readme and i could not find a way to feed the ENV file is there is any.
Can you please confirm if there a way to feed the Env File to the system?

**Comment by ouvreboite** [comment]
Hello, currently, there no way. We can only feed the collection and data files. I suppose it would be fairly straightforward to support.

**Comment by PratikThorve** [comment]
Hey @ouvreboite  is it ok we fork the repo and create our own with the EnvFile requirement ? Also i do not see any license info on the repo ,is it free to use  with no restrictions ?
